on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write  # Required for authentication with GitHub Pages

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0

      - name: Build and Run Tests
        run: mvn -B clean --file pom.xml test

      - name: Upload Extent Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports
          path: reports/
          retention-days: 7

  deploy:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Create Custom index.html
        run: |
          echo ^<^!DOCTYPE html^> > reports/index.html
          echo ^<html lang="en"^> >> reports/index.html
          echo ^<head^>^<meta http-equiv="refresh" content="0;url=report.html"^>^</head^> >> reports/index.html
          echo ^<body^>^<p^>Redirecting to Extent Reports...^</p^>^</body^> >> reports/index.html
          echo ^</html^> >> reports/index.html

      - name: Upload Reports to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
